spring.application.name=foodAndMealTracker

# Supabase PostgreSQL connection
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.peiotjyqfufhdqasyham
spring.datasource.password=group3foodandmeal
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect